# version: '3.8'

# services:
#   backend:
#     build:
#       context: .
#       dockerfile: backend/Dockerfile
#     volumes:
#       - ./backend:/app
#     ports:
#       - "8001:8001"
#     environment:
#       - DEBUG=True
#     command: python manage.py runserver 0.0.0.0:8001


services:
  # Backend сервис
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8001:8001"
    environment:
      - DJANGO_ALLOWED_HOSTS=*
    networks:
      - app-network

  # Frontend сервис
  frontend:
    build:
      context: .
      dockerfile: frontend/front-apartment/Dockerfile
    container_name: frontend
    ports:
      - "5174:5174"
    environment:
      - REACT_APP_API_URL=http://backend:8001
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
