version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"
    environment:
      - DEBUG=True
    command: python manage.py runserver 0.0.0.0:8001

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   stdin_open: true
  #   tty: true
